// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqdqkzhngnnbzzdpjtrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZHFremhuZ25uYnp6ZHBqdHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzg5OTIsImV4cCI6MjA3MDkxNDk5Mn0.f7KtnJgXOxGTwrQXXp8EDMtJkUNezw_m9i_8IT7FAT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});